name: CodeSonar
on:
  push:                  # Only run onces the Pull request is created
    branches:
      - 'release/**'               # Feature Branches
  pull_request:
    branches:
      - 'release/**'       
  
jobs:
  CodeSonar_Analyze:
    permissions: write-all
    runs-on: self-hosted
    container:
      image: canuckmh/nginx-cso-builder:7.4p0
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    env:
      GITHUB_CAFILE: ".github/github.cert.pem" 
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      GITHUB_API_URL: https://api.github.com
      PULL_REQUEST_ID: ${{ github.event.pull_request.number }}
      ROOT_TREE: "OSS-Projects/NGINX-GitHub" 
      PROJECT_NAME: "nginx"
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
      CSONAR_HUB_URL: "https://partnerdemo.codesonar.com" 
      CSONAR_HUB_USER: "${{ secrets.CSONAR_HUB_USER }}"
      CSONAR_HUB_PASSWORD: "${{ secrets.CSONAR_HUB_PASS }}"
      CSONAR_CSHOME: /opt/codesonar
      CSO_GITHUB: /opt/codesonar-github 
      GITHUB_REPO_URL: "http://github.com/markhermeling/nginx"    # the github.repositoryUrl is not an http-link.
      TARGET: ${{ github.base_ref }}
    steps:
      - name: Set parallelism
          echo "PARALLEL=`nproc`" >> $GITHUB_ENV
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Safe directory
        run: git config --global --add safe.directory `pwd`
      - name : configure
        run: auto/configure --with-http_ssl_module
      - name: Checkout CodeSonar CI-Script
        uses: actions/checkout@v2
        with:
          repository: CodeSecure_SE/codesonar_ci
          path: .
      - name: Build and Analyze
        run: python3 ./codesonar_ci.py make -j $PARALLEL
       - name: Upload SARIF to GitHub #Use this if you do not have GitHub Enterprise
        if: ${{ github.event.pull_request }}
        uses: actions/upload-artifact@v3
        with:
          name: SARIF file
          path: warnings.sarif
      - name: Cleanup Credential File
        run: shred -u "$CSONAR_HUB_PWFILE"
      - name: Push Summary Report
        if: ${{ github.event.pull_request }}
        run: >
            "$CSPYTHON" "$CSO_GITHUB/sarif_summary.py"
            warnings.sarif
            "$CSONAR_HUB_URL"
            "$ROOT_PROJECT_NAME"
            | "$CSPYTHON" "$CSO_GITHUB/push_github_pr_comment.py"
            --api-url $GITHUB_API_URL --cafile "$GITHUB_CAFILE"
            ${{ github.repository }}
            $PULL_REQUEST_ID
            GITHUB_TOKEN
            
