name: CodeSonar
on:
  push:
jobs:
  login:
    runs-on: self-hosted
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  container-test-job:
    runs-on: self-hosted
    container:
      image: canuckmh/nginx-cso-builder:7.3p1
    steps:
      - name: See if it works
        run: uname -a && pwd && ls
